apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  namespace: '{{.Values.global.namespace}}'
spec:
  rules:
    - host: '{{.Values.global.apiHost}}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3000
